import Head from "next/head";

const SEO = ({ 
  pageTitle, 
  description, 
  image, 
  url, 
  keywords 
}) => (
  <>
    <Head>
      {/* Title Tag */}
      <title>
        {pageTitle ? `${pageTitle} - Startup Agency React Next js Template` : 'Startup Agency React Next js Template'}
      </title>
      
      {/* Meta Tags */}
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content={description || "Generated by create next app"} />
      <meta name="keywords" content={keywords || "startup, agency, react, nextjs, template, web development"} />
      <meta name="robots" content="index, follow" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <link rel="icon" href="/favicon.webp" />
      
      {/* Open Graph Meta Tags */}
      <meta property="og:title" content={pageTitle || "Startup Agency React Next js Template"} />
      <meta property="og:description" content={description || "Generated by create next app"} />
      <meta property="og:type" content="website" />
      {/* <meta property="og:url" content={url || window.location.href} /> */}
      <meta property="og:url" content={url || null} />

      <meta property="og:image" content={image || "/default-image.jpg"} />
      <meta property="og:image:alt" content={pageTitle || "Startup Agency React Next js Template"} />
      <meta property="og:site_name" content="Startup Agency" />
      
      {/* Twitter Card Meta Tags */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={pageTitle || "Startup Agency React Next js Template"} />
      <meta name="twitter:description" content={description || "Generated by create next app"} />
      <meta name="twitter:image" content={image || "/default-image.jpg"} />
      <meta name="twitter:image:alt" content={pageTitle || "Startup Agency React Next js Template"} />
      
      {/* Structured Data (JSON-LD) for SEO */}
      {/* <script type="application/ld+json">
        {`
          {
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": "${pageTitle || 'Startup Agency React Next js Template'}",
            "description": "${description || 'Generated by create next app'}",
            "url": "${url || window.location.href}",
            "image": "${image || '/default-image.jpg'}"
          }
        `}
      </script> */}
    </Head>
  </>
);

export default SEO;
